version: '3'
services:
  tedge:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        VARIANT: bullseye
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tedge-bashhistory:/commandhistory
      - device-certs:/etc/tedge/device-certs
    privileged: true

volumes:
  tedge-bashhistory:
  device-certs:
